{{- if .Values.keda.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: container-worker-scaledobject
spec:
  scaleTargetRef:
    name: container-worker
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 10
  cooldownPeriod: 60
  triggers:
    - type: redis-streams
      metadata:
        address: "redis-service:{{ .Values.redis.service.port }}"
        stream: {{ .Values.keda.streamName }}
        consumerGroup: {{ .Values.keda.consumerGroup }}
        pendingEntriesCount: {{ .Values.keda.pendingEntriesCount | quote }}
        lagThreshold: {{ .Values.keda.lagThreshold | quote }}
      authenticationRef:
        name: {{ .Release.Name }}-redis-trigger-auth
{{- end }}

{{- if .Values.keda.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Release.Name }}-redis-trigger-auth
spec:
  secretTargetRef:
    - parameter: password
      name: {{ .Values.redis.auth.passwordSecretName }}
      key: {{ .Values.redis.auth.passwordKey }}
{{- end }}

{{- if .Values.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccount.name }}
  {{- if .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.rbac.serviceAccount.annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}

{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-container-worker-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
{{- end }}

{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-container-worker-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-container-worker-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}