{{- if .Values.frontend.ingress.enabled }}
{{- $svcPort := .Values.frontend.service.port }}
{{- $annotations := .Values.frontend.ingress.annotations }}
{{- range .Values.frontend.ingress.hosts }}
{{- $host := .host }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  labels:
    app: frontend
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ $host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: frontend-service
                port:
                  number: {{ $svcPort }}
          {{- end }}
{{- end }}
{{- end }}